version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  package-and-push-chart-on-tag:
    jobs:
    #  - architect/go-build:
    #     name: go-build
    #     binary: linux-bench
    #     resource_class: large
    #     filters:
    #       tags:
    #         only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/

          image: giantswarm/linux-bench
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-linux-bench-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linux-bench"
          persist_chart_archive: true
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
