version: 2.1
orbs:
  architect: giantswarm/architect@4.27.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          name: go-build
          binary: linux-bench
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-linux-bench-to-docker
          image: "docker.io/giantswarm/linux-bench"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-linux-bench-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "linux-bench"
          persist_chart_archive: true
          requires:
            - push-linux-bench-to-docker
            # - push-starboard-exporter-to-quay
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
