apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ tpl .Values.namespace  . }}
  labels:
    app: {{ tpl .Values.name  . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ tpl .Values.name  . }}
        release: "{{ .Release.Name }}"
    spec:
      hostPID: true
      serviceAccountName: {{ .Values.name }}
      restartPolicy: Never
      securityContext:
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 6 }}
        {{- end}}
      containers:
      - name: linux-bench
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:  ["cp /linux-bench /host && cp -r /cfg /host && chroot /host && ./linux-bench --json --include-test-output --logtostderr && rm -r /cfg && rm /linux-bench && exit"]
        securityContext:
          {{- with .Values.securityContext }}
            {{- . | toYaml | nindent 8 }}
          {{- end }}
        volumeMounts:
          - name: host
            mountPath: /host
            readOnly: true
      volumes:
        - name: host
          hostPath:
            path: "/"
