apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ tpl .Values.namespace  . }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowedHostPaths:
    - pathPrefix: /
      readOnly: false
  volumes:
    - 'hostPath'
    - 'secret'
    - 'configMap'
  hostPID: true
  hostIPC: true
  privileged: true
  allowPrivilegeEscalation: true
